<div class="banner">
    <div class="wrapper row">
        <div class="banner__text">
            <h1 class="banner__title">Lorem ipsum dolor sit amet, consectetur.</h1>
            <p class="banner__paragraph">Lorem ipsum dolor sit amet, consectetur adipisicing elit. A, aliquam commodi
                eaque exercitationem numquam
                omnis
                quibusdam ratione saepe soluta tempora.</p>
            <button class="btn btn-large">I want to learn</button>
        </div>

        <div class="banner__image">
            <img src="kn.png" alt="banner image">
        </div>


    </div>

</div>