<header class="header">
    <div class="wrapper row">
        <a href="#" class="logo">
            <img src="public/img/logo.svg" alt="Logo" id="logo">
        </a>
        <nav class="nav">

            <ul class="nav__list">
                <li class="nav__item"><a class="nav__link" href="#">Home</a></li>
                <li class="nav__item"><a class="nav__link" href="#">About</a></li>
                <li class="nav__item"><a class="nav__link" href="#">Contact</a></li>
                <?php if (App::auth()): ?>
                    <li class="nav__item"><a class="nav__link" href="/dashboard/index">Dashboard</a></li>
                <?php endif; ?>
            </ul>
            <ul class="nav__list">
                <?php if (!App::auth()): ?>
                    <li><a class="nav__link" href="/index/login">Login</a></li>
                <?php else: ?>
                    <li><a class="nav__link" href="/index/logout">Logout <?php
                            echo App::operator()
                            ?></a></li>
                <?php endif; ?>
            </ul>
        </nav>
    </div>
</header>